WITH base_unida AS (
  SELECT
    codigo,
    nome,
    valorVenda,
    valorCusto,
    valorCustoMedio,
    quantidadeEstoque,
    unidade,
    codigoBarras,
    codigoLaboratorio,
    nomeLaboratorio,
    codigoGrupo,
    nomeGrupo,
    codigoPrincipioAtivo,
    nomePrincipioAtivo,
    codigoCategoria,
    nomeCategoria,
    codigoClassificacao,
    nomeClassificacao,
    ativo,
    percentualDesconto,
    percentualDescontoMax,
    tipo,
    observacaoVenda,
    integracaoEcommerce,
    nomeEcommerce,
    descricaoEcommerce,
    valorVendaEcommerce,
    quantidadeEstoqueEcommerce,
    larguraEcommerce,
    alturaEcommerce,
    profundidadeEcommerce,
    pesoEcommerce,
    corEcommerce,
    tamanhoEcommerce,
    ARRAY(
      SELECT CAST(t.element AS STRING)
      FROM UNNEST(tags.list) AS t
    ) AS tags_array,
    'produto_raw_01' AS origem_raw
  FROM `quick-woodland-453702-g2.1_raw.produto_raw_01`

  UNION ALL

  SELECT
    codigo,
    nome,
    valorVenda,
    valorCusto,
    valorCustoMedio,
    quantidadeEstoque,
    unidade,
    codigoBarras,
    codigoLaboratorio,
    nomeLaboratorio,
    codigoGrupo,
    nomeGrupo,
    codigoPrincipioAtivo,
    nomePrincipioAtivo,
    codigoCategoria,
    nomeCategoria,
    codigoClassificacao,
    nomeClassificacao,
    ativo,
    percentualDesconto,
    percentualDescontoMax,
    tipo,
    observacaoVenda,
    integracaoEcommerce,
    nomeEcommerce,
    descricaoEcommerce,
    valorVendaEcommerce,
    quantidadeEstoqueEcommerce,
    larguraEcommerce,
    alturaEcommerce,
    profundidadeEcommerce,
    pesoEcommerce,
    corEcommerce,
    tamanhoEcommerce,
    ARRAY(
      SELECT CAST(t.element AS STRING)
      FROM UNNEST(tags.list) AS t
    ) AS tags_array,
    'produto_raw_02' AS origem_raw
  FROM `quick-woodland-453702-g2.1_raw.produto_raw_02`
)

SELECT
  origem_raw,
  CAST(codigo AS STRING) AS chave_composta,
  SAFE_CAST(codigo AS INT64) AS codigo,
  nome,
  SAFE_CAST(valorVenda AS FLOAT64) AS valorVenda,
  SAFE_CAST(valorCusto AS FLOAT64) AS valorCusto,
  SAFE_CAST(valorCustoMedio AS FLOAT64) AS valorCustoMedio,
  SAFE_CAST(quantidadeEstoque AS INT64) AS quantidadeEstoque,
  unidade,
  SAFE_CAST(codigoBarras AS FLOAT64) AS codigoBarras,
  SAFE_CAST(codigoLaboratorio AS FLOAT64) AS codigoLaboratorio,
  nomeLaboratorio,
  SAFE_CAST(codigoGrupo AS INT64) AS codigoGrupo,
  nomeGrupo,
  codigoPrincipioAtivo,
  nomePrincipioAtivo,
  SAFE_CAST(codigoCategoria AS FLOAT64) AS codigoCategoria,
  nomeCategoria,
  SAFE_CAST(codigoClassificacao AS FLOAT64) AS codigoClassificacao,
  nomeClassificacao,
  SAFE_CAST(ativo AS BOOL) AS ativo,
  SAFE_CAST(percentualDesconto AS FLOAT64) AS percentualDesconto,
  SAFE_CAST(percentualDescontoMax AS FLOAT64) AS percentualDescontoMax,
  SAFE_CAST(tipo.codigo AS INT64) AS tipo_codigo,
  tipo.nome AS tipo_nome,
  observacaoVenda,
  STRING_AGG(tag, ', ' ORDER BY tag) AS tag_valor,
  SAFE_CAST(integracaoEcommerce AS BOOL) AS integracaoEcommerce,
  nomeEcommerce,
  descricaoEcommerce,
  SAFE_CAST(valorVendaEcommerce AS INT64) AS valorVendaEcommerce,
  SAFE_CAST(quantidadeEstoqueEcommerce AS INT64) AS quantidadeEstoqueEcommerce,
  SAFE_CAST(larguraEcommerce AS INT64) AS larguraEcommerce,
  SAFE_CAST(alturaEcommerce AS INT64) AS alturaEcommerce,
  SAFE_CAST(profundidadeEcommerce AS INT64) AS profundidadeEcommerce,
  SAFE_CAST(pesoEcommerce AS INT64) AS pesoEcommerce,
  SAFE_CAST(corEcommerce AS INT64) AS corEcommerce,
  SAFE_CAST(tamanhoEcommerce AS INT64) AS tamanhoEcommerce

FROM base_unida
LEFT JOIN UNNEST(tags_array) AS tag

GROUP BY
  origem_raw,
  codigo,
  nome,
  valorVenda,
  valorCusto,
  valorCustoMedio,
  quantidadeEstoque,
  unidade,
  codigoBarras,
  codigoLaboratorio,
  nomeLaboratorio,
  codigoGrupo,
  nomeGrupo,
  codigoPrincipioAtivo,
  nomePrincipioAtivo,
  codigoCategoria,
  nomeCategoria,
  codigoClassificacao,
  nomeClassificacao,
  ativo,
  percentualDesconto,
  percentualDescontoMax,
  tipo,
  tipo.codigo,
  tipo.nome,
  observacaoVenda,
  integracaoEcommerce,
  nomeEcommerce,
  descricaoEcommerce,
  valorVendaEcommerce,
  quantidadeEstoqueEcommerce,
  larguraEcommerce,
  alturaEcommerce,
  profundidadeEcommerce,
  pesoEcommerce,
  corEcommerce,
  tamanhoEcommerce